---
title: "10.10 case study"
author: "Yuqing Liu"
date: "2023-10-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggridges)
library(leaflet)
```

```{r}
library(p8105.datasets)

data(nyc_airbnb)
```

```{r}
# View(nyc_airbnb)
str(nyc_airbnb)
```

```{r}
nyc_airbnb |>
  count(room_type)
```

```{r}
nyc_airbnb |>
  count(neighbourhood_group)
```
## Brainstorm questions
- Where are Airbnbs expensive?
  - Borogh? Neighborhood?
  - Do other factors affect price? What about rating?

```{r}
nyc_airbnb |> group_by(review_scores_location)|>
  summarize(
    mean_price = mean(price, na.rm = TRUE),
    mean_price = mean(price, na.rm = TRUE),
    median_price = median(price),
    sd_tmax = sd(price))
```

```{r}
nyc_airbnb |> group_by(neighbourhood_group, room_type)|>
  summarize(
    median_price = median(price))|>
    pivot_wider(names_from = room_type,
                values_from = median_price)
```

```{r}
nyc_airbnb |> 
  filter(
    price<1000,
    room_type == "Entire home/apt",
    neighbourhood_group == "Manhattan")|>
  group_by(neighbourhood)|>
  summarize(
    n_apt = n(),
    mean_price = mean(price))|>
  arrange((mean_price)) # sort mean_price
```

```{r}
nyc_airbnb |> 
  filter(
    price<1000,
    room_type == "Entire home/apt",
    neighbourhood_group == "Manhattan")|>
  mutate(neighbourhood = fct_reorder(neighbourhood, price))|>
  ggplot(aes(x = price, y = neighbourhood)) +
  geom_density_ridges()
```


```{r}
nyc_airbnb |> 
  filter(
    price<1000,
    room_type == "Entire home/apt",
    neighbourhood_group == "Manhattan")|>
  sample_n(50)|>
  leaflet()|>
  addTiles()|>
  addMarkers(~lat, ~long)
```





